MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Controllers/AuthorsController.cs
using CRUD_Porject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace CRUD_Porject.Controllers
{
    [Authorize]
    public class AuthorsController : Controller
    {
        readonly BookSellerDbContext database = new BookSellerDbContext();
        // GET: Authors
        public ActionResult Index()
        {
            return View(database.Authors.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateAuthor()
        {
            return PartialView("_CreateAuthor");
        }
        [HttpPost]
        public PartialViewResult CreateAuthor(Author a)
        {
            Thread.Sleep(4000);
            if (ModelState.IsValid)
            {
                database.Authors.Add(a);
                database.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditAuthor(int id)
        {
            var b = database.Authors.First(x => x.AuthorID == id);
            return PartialView("_EditAuthor", b);
        }
        [HttpPost]
        public PartialViewResult EditAuthor(Author a)
        {
            Thread.Sleep(4000);
            if (ModelState.IsValid)
            {
                database.Entry(a).State = EntityState.Modified;
                database.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(database.Authors.First(x => x.AuthorID == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DoDelete(int AuthorId)
        {
            var a = new Author { AuthorID = AuthorId };
            database.Entry(a).State = EntityState.Deleted;
            database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Controllers/BooksController.cs
using CRUD_Porject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.Web.Mvc;
using CRUD_Porject.ViewModel;
using System.IO;

namespace CRUD_Porject.Controllers
{
    [Authorize]
    public class BooksController : Controller
    {
        private readonly BookSellerDbContext db = new BookSellerDbContext();
        // GET: Books
        public ActionResult Index()
        {
            var data = db.Books
                .Include(x=>x.BookAuthors.Select(y => y.Author))
                .ToList();

            return View(data);
        }
        public ActionResult Create()
        {
            ViewBag.Publishers = db.Publishers.ToList();
            ViewBag.Genres = db.Genres.ToList();
            var data = new BookInputModel();
            data.Authors.Add(new AuthorViewModel());
            return View(data);
        }
        [HttpPost]
        public ActionResult Create(BookInputModel model, int[] AuthorID)
        {
            if (ModelState.IsValid)
            {
                var ba = new Book
                {
                    BookName = model.Title,
                    Price = model.Price,
                    PublishDate = model.PublishDate,
                    Available = model.Available,
                    GenreID = model.GenreID,
                    PublisherID = model.PublisherID,
                   
                };

               foreach(var i in AuthorID)
                {
                    ba.BookAuthors.Add(new BookAuthor { AuthorID = i });
                }
                if (model.Picture.ContentLength > 0)
                {
                    string ext = Path.GetExtension(model.Picture.FileName);
                    string fileName = Guid.NewGuid() + ext;
                    model.Picture.SaveAs(Path.Combine(Server.MapPath("~/Uploads"), fileName));
                    ba.Picture = fileName;
                }
                db.Books.Add(ba);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
           
            ViewBag.Genres = db.Genres.ToList();

            return View(model);
        }
        public JsonResult GetAddress(int id)
        {
            var t = db.Authors.FirstOrDefault(x => x.AuthorID == id);
            return Json(t.AuthorAddress);
        }
        public ActionResult CreateNewField(BookInputModel data)
        {
            ViewBag.Authors = db.Authors.ToList();
            
            return PartialView();
        }
    }
}

MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Controllers/GenresController.cs
using CRUD_Porject.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace CRUD_Porject.Controllers
{
    [Authorize]
    public class GenresController : Controller
    {
        readonly BookSellerDbContext database = new BookSellerDbContext();
        // GET: Authors
        public ActionResult Index()
        {
            return View(database.Genres.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateGenre()
        {
            return PartialView("_CreateGenre");
        }
        [HttpPost]
        public PartialViewResult CreateGenre(Genre g)
        {
            Thread.Sleep(2000);
            if (ModelState.IsValid)
            {
                database.Genres.Add(g);
                database.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditGenre(int id)
        {
            var b = database.Genres.First(x => x.GenreID == id);
            return PartialView("_EditGenre", b);
        }
        [HttpPost]
        public PartialViewResult EditGenre(Genre g)
        {
            Thread.Sleep(2000);
            if (ModelState.IsValid)
            {
                database.Entry(g).State = EntityState.Modified;
                database.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(database.Genres.First(x => x.GenreID == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DoDelete(int GenreID)
        {
            var a = new Genre { GenreID = GenreID };
            database.Entry(a).State = EntityState.Deleted;
            database.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Controllers/SalesController.cs
using CRUD_Porject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using CRUD_Porject.ViewModel;

namespace CRUD_Porject.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private readonly BookSellerDbContext db = new BookSellerDbContext();
        // GET: Sales
        public ActionResult Index()
        {
            var data = db.Customers
                .Include(x => x.Sales.Select(y => y.Book))
                .ToList();

            return View(data);
        }
        public ActionResult Create()
        {
            ViewBag.Customers = db.Customers.ToList();
            var data = new CustomerSaleInputModel();
            data.CustomerBooks.Add(new CustomerBookViewModel());
            return View(data);
        }
        [HttpPost]
        public ActionResult Create(CustomerSaleInputModel model, int[] BookID)
        {
            if (ModelState.IsValid)
            {
                var c = new Customer
                {
                    CustomersName = model.CustomersName,
                
                };

                foreach (var i in BookID)
                {
                    c.Sales.Add(new SaleDetail { BookID = i });
                }
                
                db.Customers.Add(c);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Customers = db.Customers.ToList();
            return View(model);
        }
        public ActionResult CreateNewField(CustomerSaleInputModel data)
        {
            ViewBag.Books = db.Books.ToList();

            return PartialView();
        }
    }
}

MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Views/Shared/_Fail.cshtml
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Failed!</strong> failed to perform requested operation.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ASP.NET MVC CRUD</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <style>

        body {
            background-color: linen;
            padding-top: 70px;
        }
       
    </style>
    @RenderSection("styles", false)

</head>
<body>
    <nav class="navbar navbar-light  navbar-expand-lg fixed-top  shadow-sm" style="background-color:aquamarine;">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggler" 
                    aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <span class="navbar-brand">Monthly<sup>Exam</sup><sub>08</sub></span>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <ul class="navbar-nav nav ">
                    <li class="nav-item ">
                        @Html.ActionLink("Home", "Index", "Home", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Author", "Index", "Authors", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Genre", "Index", "Genres", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Publisher", "Index", "Publishers", new { }, new { @class = "nav-link" })
                    </li>
                    @*<li class="nav-item ">
                        @Html.ActionLink("Customer", "Index", "Customers", new { }, new { @class = "nav-link" })
                    </li>*@
                    <li class="nav-item ">
                        @Html.ActionLink("Book", "Index", "Books", new { }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item ">
                        @Html.ActionLink("Sale", "Index", "Sales", new { }, new { @class = "nav-link" })
                    </li>
                </ul>
                @if (Request.IsAuthenticated)
                {
                    <ul class="navbar-nav nav ms-auto">

                        <li class="nav-item">
                            @Html.ActionLink("Logout", "Logout", "Account", new { }, new { @class = "nav-link" })
                        </li>


                    </ul>

                }
                else
                {
                    <ul class="navbar-nav nav ms-auto">
                        <li class="nav-item">
                            @Html.ActionLink("Register", "Register", "Account", new { }, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Login", "Login", "Account", new { }, new { @class = "nav-link" })
                        </li>


                    </ul>
                }
            </div>
        </div>
    </nav>
    <section class="container-fluid main">
        @RenderBody()
    </section>
    <footer class="container-fluid">
        <p>ID:1268006</p>
        <p>Name: Md.Maruf Billah</p>
    </footer>
    @RenderSection("scripts", false)
</body>
</html>

MVC_CRUD_Project/CRUD_Porject_Works/CRUD_Porject/Views/Shared/_Success.cshtml
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Success!</strong> Operation performed successfully.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>